
////////////////////////////////////////////////////////////////////////////////////////////////////
//
//    Fin_ParserTables.hpp (generated by LRSTAR 24.0.025)

#include "Fin_Actions.h"
#include "Fin_ParserTables.h"

static int n_terms = 34;      // Number of terminals.
static int n_heads = 48;      // Number of nonterminals.
static int n_prods = 104;     // Number of productions.
static int n_states = 53;     // Number of states.
static int accept_state = 52; // Accept state.
static int n_termactns = 1;   // Number of terminal actions.
static int n_nodenames = 0;   // Number of node names.
static int n_nodeactns = 0;   // Number of node actions.
static int eof_symb = 1;      // <eof> symbol number.
static int err_used = 0;      // <error> used in grammar?

// Terminal symbols of the grammar ...
char* Fin_ParserTables::term_symb[34] = {
    "<error>",       "<eof>",        "\'!\'",      "\'}\'",        "\']\'",         "\':\'",
    "\',\'",         "\')\'",        "<ctid>",     "\'=\'",        "\';;\'",        "\'impl\'",
    "\'inline\'",    "\'linkable\'", "\'linked\'", "\'naked\'",    "\'noreturn\'",  "\'{\'",
    "\'[\'",         "\'(\'",        "\'(*\'",     "<rtid>",       "\'*\'",         "\'*)\'",
    "\'struct\'",    "<mlopen>",     "<mlclose>",  "\'enumDecl\'", "\'unionDecl\'", "\'interfaceDecl\'",
    "\'faultDecl\'", "\'typeSig\'",  "\'expr\'",   "\'stmt\'"
};

// Nonterminal symbols of the grammar ...
char* Fin_ParserTables::head_symb[48] = {
    "srcFile",
    "mlcomment",
    "mlbody",
    "decl",
    "ctDecl",
    "ctids",
    "rtDecl",
    "rtids",
    "funcDecl",
    "contracts",
    "ctParams",
    "params",
    "param",
    "funcParams",
    "fields",
    "field",
    "attributes",
    "body",
    "structDecl",
    "implBlock",
    "(mlcomment | decl)",
    "(mlcomment | decl)+",
    "(mlbody | mlcomment)",
    "(mlbody | mlcomment)*",
    "('=' expr)",
    "('=' expr)?",
    "'!'?",
    "ctParams?",
    "('(*' '*)')",
    "('(*' '*)')*",
    "(',' param)",
    "(',' param)*",
    "','?",
    "(':' expr)",
    "(':' expr)?",
    "'*'?",
    "(',' fields)",
    "(',' fields)?",
    "(<rtid> '*'? (',' fields)? | fields)",
    "(<rtid> '*'? (',' fields)? | fields)?",
    "(',' field)",
    "(',' field)*",
    "('inline' | 'linkable' | 'linked' | 'naked' | 'noreturn')",
    "('inline' | 'linkable' | 'linked' | 'naked' | 'noreturn')*",
    "stmt*",
    "fields?",
    "funcDecl*",
    "implBlock*"
};

// Terninal action names found in the grammar ...
char* Fin_ParserTables::tact_name[1] = {"lookup"};

// Head symbol numbers for the productions ...
uchar Fin_ParserTables::head_numb[104] = {0,  1,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,
                                          2,  2,  2,  2,  2,  2,  2,  3,  3,  3,  3,  3,  3,  3,  3,  4,  5,  5,
                                          6,  7,  7,  8,  9,  10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 20, 21,
                                          21, 22, 22, 23, 23, 24, 25, 25, 26, 26, 27, 27, 28, 29, 29, 30, 31, 31,
                                          32, 32, 33, 34, 34, 35, 35, 36, 37, 37, 38, 38, 39, 39, 40, 41, 41, 42,
                                          42, 42, 42, 42, 43, 43, 44, 44, 45, 45, 46, 46, 47, 47};

// First tail symbol index into the tail list ...
uchar Fin_ParserTables::f_tail[105] = {0,   2,   5,   6,   7,   8,   9,   10,  11,  12,  13,  14,  15,  16,  17,
                                       18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,  29,  30,  31,  32,
                                       33,  34,  35,  36,  39,  40,  43,  46,  47,  50,  59,  60,  63,  66,  69,
                                       72,  75,  78,  79,  80,  88,  92,  93,  94,  95,  97,  98,  99,  99,  101,
                                       103, 103, 104, 104, 105, 105, 106, 108, 108, 110, 112, 112, 114, 114, 115,
                                       117, 117, 118, 118, 119, 121, 121, 122, 125, 126, 126, 127, 129, 129, 131,
                                       132, 133, 134, 135, 136, 136, 138, 138, 140, 140, 141, 141, 143, 143, 145};

// Tail symbol numbers ...
char Fin_ParserTables::tail[145] = {-21, 1,   25,  -23, 26,  2,   3,   4,   5,   6,   7,   8,   9,   10,  11,  12,  13,
                                    14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  -4,  -6,  -8,  -18, 27,  28,
                                    29,  30,  -5,  31,  -25, 8,   -5,  6,   8,   -7,  31,  -25, 21,  -7,  6,   21,  -9,
                                    31,  -26, 21,  -27, -13, -16, -17, 10,  -29, 18,  -11, 4,   -12, -31, -32, -5,  31,
                                    -34, 19,  -39, 7,   -15, -41, -32, -7,  31,  -34, -43, -44, 24,  8,   -27, 17,  -45,
                                    -46, -47, 3,   11,  -5,  5,   -46, -1,  -3,  -20, -21, -20, -2,  -1,  -23, -22, 9,
                                    32,  -24, 2,   -10, 20,  23,  -29, -28, 6,   -12, -31, -30, 6,   5,   32,  -33, 22,
                                    6,   -14, -36, 21,  -35, -37, -14, -38, 6,   -15, -41, -40, 12,  13,  14,  15,  16,
                                    -43, -42, -44, 33,  -14, -46, -8,  -47, -19};

// Arguments for token actions ...
char Fin_ParserTables::arga[34] = {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
                                   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1};

// Boolean matrix ...
uchar Fin_ParserTables::Bm[52] = {0,  0, 0, 0, 1, 41,  2, 1, 41, 64,  0,   64, 0,  0,  64, 0, 128, 0,
                                  0,  1, 0, 2, 0, 4,   0, 0, 4,  252, 255, 31, 0,  32, 0,  0, 128, 0,
                                  16, 0, 0, 8, 0, 128, 0, 0, 2,  8,   0,   0,  96, 0,  0,  0};

// Booeal matrix row (for state)...
uchar Fin_ParserTables::Br[53] = {3,  6,  9,  9,  12, 15, 0,  18, 20, 18, 20, 17, 23, 24, 27, 30, 32, 17,
                                  35, 18, 30, 17, 36, 0,  9,  10, 0,  0,  9,  11, 31, 0,  17, 0,  11, 31,
                                  18, 32, 0,  38, 41, 42, 45, 17, 22, 1,  11, 18, 17, 48, 0,  0,  0};

// Booolean matrix column (displacement) ...
uchar Fin_ParserTables::Bc[34] = {0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1,
                                  1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3};

// Boolean matrix filter/mask value ...
uchar Fin_ParserTables::Bf[34] = {1,  2,  4,  8,   16, 32, 64, 128, 1, 2,  4,  8,  8,  8,  8,  8,   8,
                                  16, 32, 64, 128, 1,  2,  4,  8,   8, 16, 32, 32, 32, 32, 64, 128, 1};

// Terminal transition matrix ...
char Fin_ParserTables::Tm[89] = {0,   0,   0,   0,   48,  43,  36,  49,  15,  11,  0,   24,  50,  9,   0,
                                 -35, 41,  -38, 0,   0,   28,  52,  0,   12,  20,  11,  35,  2,   0,   0,
                                 30,  0,   0,   0,   0,   0,   3,   0,   0,   7,   6,   -54, 10,  -74, -58,
                                 -58, -58, -58, -58, -58, -58, -58, -58, -58, -58, -58, -58, -58, -58, -58,
                                 -58, -58, -58, 6,   -1,  17,  -49, -41, 37,  9,   -44, 2,   16,  -39, 47,
                                 -95, 21,  19,  32,  13,  3,   46,  -66, 7,   6,   1,   8,   -59, -97};

// Terminal transition matrix row ...
uchar Fin_ParserTables::Tr[53] = {65, 21, 65, 21, 2,  65, 65, 2,  65, 9,  65, 2, 65, 65, 44, 65, 65, 9,
                                  65, 5,  65, 5,  65, 65, 9,  65, 65, 65, 5,  2, 65, 65, 1,  65, 1,  65,
                                  5,  21, 65, 65, 65, 65, 65, 5,  65, 65, 0,  1, 5,  9,  65, 65, 65};

// Terminal transition matrix column ...
uchar Fin_ParserTables::Tc[34] = {0,  0,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9,  10, 10, 10, 10, 10,
                                  11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 20, 20, 20, 20, 21, 22, 23};

// Nonterminal transition matrix ...
char Fin_ParserTables::Nm[102] = {49, 28,  -86,  28,  27,  24, 28,  27, 0,   0,  0,   0,   0,  0,    0,  0,   0,
                                  0,  0,   -79,  0,   40,  40, -69, 2,  3,   0,  -54, -54, 0,  0,    25, 0,   5,
                                  0,  0,   -45,  -46, 0,   0,  4,   0,  -88, 0,  0,   0,   0,  0,    51, -36, 24,
                                  28, 27,  -101, -58, -58, 0,  22,  0,  5,   0,  0,   0,   0,  0,    0,  4,   26,
                                  23, 0,   0,    0,   0,   26, 0,   42, 2,   3,  44,  1,   1,  -103, 17, 18,  -68,
                                  5,  -71, 29,   -42, -43, 46, -82, 4,  38,  31, 34,  -95, 39, 45,   14, 33,  -33};

// Nonterminal transition matrix row ...
uchar Fin_ParserTables::Nr[53] = {76, 24, 76, 76, 76, 76, 76, 76, 76, 76, 24, 76, 76, 76, 50, 76, 76, 76,
                                  76, 50, 24, 50, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 5,  50, 24, 24,
                                  5,  76, 76, 76, 76, 76, 76, 0,  76, 76, 76, 0,  2,  76, 24, 50, 76};

// Nonterminal transition matrix column ...
uchar Fin_ParserTables::Nc[104] = {4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,
                                   4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  0,  0,  4,  1,  1,  3,  16, 7,
                                   7,  18, 18, 17, 2,  17, 2,  4,  5,  3,  3,  4,  4,  5,  5,  23, 23, 25, 25, 25, 6,
                                   6,  7,  7,  8,  9,  9,  10, 11, 11, 12, 12, 13, 13, 13, 14, 14, 15, 15, 15, 16, 16,
                                   17, 17, 18, 19, 19, 20, 20, 20, 20, 20, 21, 21, 22, 22, 23, 23, 24, 24, 25, 25};

// Reduction matrix ...
uchar Fin_ParserTables::Rm[19] = {0, 0, 0, 0, 0, 102, 0, 67, 67, 0, 0, 77, 0, 37, 0, 50, 0, 67, 67};

// Reduction matrix row ...
char Fin_ParserTables::Rr[53] = {67, 67, 0,  0,  0, 40, 57, 0,  60,  0,  60, 0,  62, 0,  0,   64,  0,  0,
                                 0,  0,  64, 98, 0, 70, 0,  0,  100, 87, 0,  72, 75, 94, 84,  -4,  72, 75,
                                 73, 0,  96, 47, 0, -9, 0,  73, 0,   48, 80, 0,  0,  0,  100, -14, 0};

// Reduction matrix column ...
uchar Fin_ParserTables::Rc[34] = {0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0, 0, 0,
                                  0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0};

// Production lengths (minus one) ...
char Fin_ParserTables::PL[104] = {1,  2,  0, 0,  0,  0, 0, 0,  0, 0,  0,  0, 0,  0, 0,  0,  0,  0,  0,  0, 0,
                                  0,  0,  0, 0,  0,  0, 0, 0,  0, 0,  0,  0, 2,  0, 2,  2,  0,  2,  8,  0, 2,
                                  2,  2,  2, 2,  2,  0, 0, 7,  3, 0,  0,  0, 1,  0, 0,  -1, 1,  1,  -1, 0, -1,
                                  0,  -1, 0, 1,  -1, 1, 1, -1, 1, -1, 0,  1, -1, 0, -1, 0,  1,  -1, 0,  2, 0,
                                  -1, 0,  1, -1, 1,  0, 0, 0,  0, 0,  -1, 1, -1, 1, -1, 0,  -1, 1,  -1, 1};

// Nondeterministic first terminal in the list ...
uchar Fin_ParserTables::nd_fterm[54] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                                        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                                        0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1};

// Nondeterministic terminal list ...
uchar Fin_ParserTables::nd_term[1] = {6};

// Nondeterministic first action in the list ...
uchar Fin_ParserTables::nd_faction[2] = {0, 2};

// Nondeterministic actions list ...
char Fin_ParserTables::nd_action[2] = {-37, -77};
// Terminal action number ...
char Fin_ParserTables::tact_numb[34] = {-1, -1, -1, -1, -1, -1, -1, -1, 0,  -1, -1, -1, -1, -1, -1, -1, -1,
                                        -1, -1, -1, -1, 0,  -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1};

// Init action function pointers ...
void (*Fin_ParserTables::init_func[2])() = {Fin_Actions::init_actions, Fin_Actions::term_actions};

// Terminal action function pointers ...
int (*Fin_ParserTables::tact_func[1])(int& t) = {Fin_TermActions::lookup};

//
////////////////////////////////////////////////////////////////////////////////////////////////////
