
////////////////////////////////////////////////////////////////////////////////
//
//    Fin_LexerTables.h (generated by DFA 24.0.025)

#pragma once

#undef LEXER
#undef DEBUG_LEXER

#define LEXER Fin_Lexer

/*
      static uchar  Tm[  4841]        ; // Terminal transition matrix.
      static ushort Tr[   117]        ; // Terminal transition matrix row.
      static uchar  Tc[   256]        ; // Terminal transition matrix column.
      static char   term_numb[   117] ; // Terminal number.
*/

//
////////////////////////////////////////////////////////////////////////////////
