
////////////////////////////////////////////////////////////////////////////////
//
//    Fin_ParserTables.h (generated by LRSTAR 24.0.025)

#pragma once

#undef GRAMMAR
#undef PARSER
#undef PARSER_TABLES
#undef LEXER
#undef ACTIONS
#undef TERM_ACTIONS
#undef NODE_ACTIONS
#undef INSENSITIVE
#undef LOOKAHEADS
#undef DEBUG_PARSER
#undef DEBUG_TRACE
#undef MAKE_AST
#undef EXPECTING
#undef REVERSABLE
#undef SEMANTICS
#undef ND_PARSING
#undef ND_THREADS

#define GRAMMAR "Fin"
#define PARSER Fin_Parser
#define PARSER_TABLES Fin_ParserTables
#define LEXER Fin_Lexer
#define ACTIONS Fin_Actions
#define TERM_ACTIONS Fin_TermActions
#define LOOKAHEADS 2
#define EXPECTING
#define ND_PARSING
#define ND_THREADS 2

enum termcon {
    VOID = 2,
    BOOL = 3,
    HALF = 4,
    BHALF = 5,
    FLOAT = 6,
    DOUBLE = 7,
    SCHAR = 8,
    SHORT = 9,
    INT = 10,
    LONG = 11,
    XLONG = 12,
    REG = 13,
    CHAR = 14,
    USHORT = 15,
    UINT = 16,
    ULONG = 17,
    UXLONG = 18,
    UREG = 19,
    ALIAS = 20,
    AMP = 21,
    AND = 22,
    ATCNAME = 23,
    ATEXPORT = 24,
    ATEXTERN = 25,
    ATINLINE = 26,
    ATNAKED = 27,
    ATNORETURN = 28,
    ATPRIV = 29,
    BANG = 30,
    BANG_BANG = 31,
    BANG_EQUALS = 32,
    CARROT = 33,
    CBRACE = 34,
    CBRACK = 35,
    COLON = 36,
    COMMA = 37,
    CPAREN = 38,
    CTID = 39,
    DOT = 40,
    DOT_DOT = 41,
    DYN = 42,
    ELLIPSES = 43,
    ENUM = 44,
    EQUALS = 45,
    EQUALS_EQUALS = 46,
    EXTEND = 47,
    FAULT = 48,
    FIN = 49,
    GREATERT = 50,
    GREATERT_EQUALS = 51,
    GREATERT_GREATERT = 52,
    GREATERT_GREATERT_PCENT = 53,
    IMPL = 54,
    INTERFACE = 55,
    LESST = 56,
    LESST_EQUALS = 57,
    LESST_LESST = 58,
    LESST_LESST_PCENT = 59,
    MINUS = 60,
    MODULE = 61,
    OBRACE = 62,
    OBRACK = 63,
    OPAREN = 64,
    OPAREN_PCENT = 65,
    OR = 66,
    PCENT = 67,
    PCENT_CPAREN = 68,
    PIPE = 69,
    PLUS = 70,
    POUND = 71,
    QMARK = 72,
    RTID = 73,
    SLASH = 74,
    STAR = 75,
    STRUCT = 76,
    TYPE = 77,
    USCORE = 78
};

typedef unsigned int uint;
typedef unsigned char uchar;
typedef unsigned short ushort;

#define TOP_DOWN 0
#define PASS_OVER 1
#define BOTTOM_UP 2

class Fin_ParserTables {
    friend class Fin_Parser;

  public:
    static char* term_symb[81];  // Terminal symbols of the grammar.
    static char* head_symb[81];  // Nonterminal symbols of the grammar.
    static char* tact_name[1];   // Terminal action names found in the grammar.
    static uchar head_numb[192]; // Head symbol number for a production.
    static ushort f_tail[193];   // First tail in a production.
    static char tail[297];       // Tail symbol number.
    static char arga[81];        // Arguments for terminal actions.

  private:
    static uchar Bm[119]; // Boolean matrix.
    static uchar Br[113]; // Boolean matrix row.
    static uchar Bc[81];  // Boolean matrix column.
    static uchar Bf[81];  // Boolean matrix filter/mask.
    static short Tm[222]; // Terminal transition matrix.
    static uchar Tr[113]; // Terminal transition matrix row.
    static uchar Tc[81];  // Terminal transition matrix column.
    static short Nm[179]; // Nonterminal transition matrix.
    static uchar Nr[113]; // Nonterminal transition matrix row.
    static uchar Nc[192]; // Nonterminal transition matrix column.
    static uchar Rm[166]; // Reduction matrix.
    static short Rr[113]; // Reduction matrix row.
    static uchar Rc[81];  // Reduction matrix column.
    static char PL[192];  // Production length minus one.

    static uchar nd_fterm[114];   // ND: first terminal in the list.
    static uchar nd_term[110];    // ND: terminal list.
    static uchar nd_faction[111]; // ND: first action in the list.
    static short nd_action[220];  // ND: action list.

    static char tact_numb[81]; // Terminal action numbers.

    static void (*init_func[2])();      // Init action function pointers.
    static int (*tact_func[1])(int& t); // Terminal action function pointers.
};

//
////////////////////////////////////////////////////////////////////////////////
