
////////////////////////////////////////////////////////////////////////////////
//
//    Fin_ParserTables.h (generated by LRSTAR 24.0.025)

#pragma once

#undef GRAMMAR
#undef PARSER
#undef PARSER_TABLES
#undef LEXER
#undef ACTIONS
#undef TERM_ACTIONS
#undef NODE_ACTIONS
#undef INSENSITIVE
#undef LOOKAHEADS
#undef DEBUG_PARSER
#undef DEBUG_TRACE
#undef MAKE_AST
#undef EXPECTING
#undef REVERSABLE
#undef SEMANTICS
#undef ND_PARSING
#undef ND_THREADS

#define GRAMMAR "Fin"
#define PARSER Fin_Parser
#define PARSER_TABLES Fin_ParserTables
#define LEXER Fin_Lexer
#define ACTIONS Fin_Actions
#define TERM_ACTIONS Fin_TermActions
#define LOOKAHEADS 2
#define EXPECTING
#define ND_PARSING
#define ND_THREADS 2

enum termcon {
    BANG = 2,
    CBRACE = 3,
    CBRACK = 4,
    COLON = 5,
    COMMA = 6,
    CPAREN = 7,
    CTID = 8,
    EQUALS = 9,
    FIN = 10,
    IMPL = 11,
    INLINE = 12,
    LINKABLE = 13,
    LINKED = 14,
    NAKED = 15,
    NORETURN = 16,
    OBRACE = 17,
    OBRACK = 18,
    OPAREN = 19,
    OPAREN_STAR = 20,
    RTID = 21,
    STAR = 22,
    STAR_CPAREN = 23,
    STRUCT = 24
};

typedef unsigned int uint;
typedef unsigned char uchar;
typedef unsigned short ushort;

#define TOP_DOWN 0
#define PASS_OVER 1
#define BOTTOM_UP 2

class Fin_ParserTables {
    friend class Fin_Parser;

  public:
    static char* term_symb[34];  // Terminal symbols of the grammar.
    static char* head_symb[48];  // Nonterminal symbols of the grammar.
    static char* tact_name[1];   // Terminal action names found in the grammar.
    static uchar head_numb[104]; // Head symbol number for a production.
    static uchar f_tail[105];    // First tail in a production.
    static char tail[145];       // Tail symbol number.
    static char arga[34];        // Arguments for terminal actions.

  private:
    static uchar Bm[52];  // Boolean matrix.
    static uchar Br[53];  // Boolean matrix row.
    static uchar Bc[34];  // Boolean matrix column.
    static uchar Bf[34];  // Boolean matrix filter/mask.
    static char Tm[89];   // Terminal transition matrix.
    static uchar Tr[53];  // Terminal transition matrix row.
    static uchar Tc[34];  // Terminal transition matrix column.
    static char Nm[102];  // Nonterminal transition matrix.
    static uchar Nr[53];  // Nonterminal transition matrix row.
    static uchar Nc[104]; // Nonterminal transition matrix column.
    static uchar Rm[19];  // Reduction matrix.
    static char Rr[53];   // Reduction matrix row.
    static uchar Rc[34];  // Reduction matrix column.
    static char PL[104];  // Production length minus one.

    static uchar nd_fterm[54];  // ND: first terminal in the list.
    static uchar nd_term[1];    // ND: terminal list.
    static uchar nd_faction[2]; // ND: first action in the list.
    static char nd_action[2];   // ND: action list.

    static char tact_numb[34]; // Terminal action numbers.

    static void (*init_func[2])();      // Init action function pointers.
    static int (*tact_func[1])(int& t); // Terminal action function pointers.
};

//
////////////////////////////////////////////////////////////////////////////////
