module fin;

fn int main(String[] args) {
    switch (args[1]) {
    case "cc":
        io::printn("cc unimplemented.");
    case "cxx":
        io::printn("cxx unimplemented.");
    case "cl":
        io::printn("cl unimplemented.");
    case "as":
        io::printn("as unimplemented.");
    case "ld":
        io::printn("ld unimplemented.");
    case "lsp":
        io::printn("lsp unimplemented.");
    case "fmt":
        io::printn("fmt unimplemented.");
    case "env":
        io::printn("env unimplemented.");
    }
    return 0;
}
